"use client";

import { useEffect, useState, type FormEvent } from "react";
import { apiRequest, getErrorMessage } from "@/lib/api";
import { useRecruiterApp } from "./app-shell";
import { EmptyState, ErrorState, Input, MetricCard, PageSkeleton, Table } from "./ui";

type Analytics = { hiringFunnel: { candidates: number; invited: number; started: number; completed: number }; completion: { total: number; completed: number; rate: number }; scoreDistribution: { label: string; count: number }[]; competencyDistribution: { name: string; averageScore: number; count: number }[]; duration: { averageMinutes: number | null; completedSamples: number }; dropOff: { state: string; count: number }[]; assessmentPerformance: { assessmentId: string; title: string; interviews: number; averageScore: number | null }[] };
function Bars({ items }: { items: { label: string; value: number; detail?: string }[] }) { const max = Math.max(1, ...items.map((item) => item.value)); return <div className="space-y-4">{items.map((item) => <div key={item.label}><div className="mb-1 flex justify-between text-xs"><span>{item.label}</span><span className="text-[#888]">{item.detail ?? item.value}</span></div><div className="h-2 bg-[#292929]"><div className="h-full bg-[#ff4d1c]" style={{ width: `${item.value / max * 100}%` }} /></div></div>)}</div>; }
export function AnalyticsView() {
  const { organization } = useRecruiterApp(); const organizationId = organization?.id ?? ""; const [range, setRange] = useState({ from: "", to: "" }); const [retry, setRetry] = useState(0); const key = `${organizationId}:${range.from}:${range.to}`; const [state, setState] = useState<{ key: string; data: Analytics | null; error: string }>({ key: "", data: null, error: "" });
  useEffect(() => { if (!organizationId) return; let active = true; const params = new URLSearchParams(); if (range.from) params.set("from", range.from); if (range.to) params.set("to", range.to); apiRequest<Analytics>(`/organizations/${organizationId}/analytics?${params}`, {}, organizationId).then((data) => active && setState({ key, data, error: "" })).catch((error) => active && setState({ key, data: null, error: getErrorMessage(error) })); return () => { active = false; }; }, [organizationId, range, key, retry]);
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setRange({ from: String(data.get("from") ?? ""), to: String(data.get("to") ?? "") }); }
  if (!organization) return <EmptyState title="No organization available" description="Select an organization to view analytics." />; if (state.key !== key) return <PageSkeleton />; if (state.error || !state.data) return <ErrorState message={state.error} onRetry={() => setRetry((value) => value + 1)} />; const data = state.data;
  return <div className="space-y-8"><header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#ff4d1c]">Measured outcomes</p><h1 className="mt-2 text-3xl font-semibold">Hiring analytics</h1><p className="mt-2 text-sm text-[#8e8a84]">Database-backed activity for {organization.name}.</p></div><form onSubmit={filter} className="flex flex-wrap items-end gap-3"><Input name="from" type="date" label="From" defaultValue={range.from} /><Input name="to" type="date" label="To" defaultValue={range.to} /><button className="btn-orange h-11 px-4 text-xs">Apply range</button></form></header>
    {!data.completion.total && !data.hiringFunnel.candidates ? <EmptyState title="No activity in this period" description="Analytics will populate as candidates and interviews move through the hiring process." /> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Candidates" value={data.hiringFunnel.candidates} detail="Added in range" /><MetricCard label="Interviews" value={data.hiringFunnel.invited} detail="Created in range" /><MetricCard label="Completion" value={`${Math.round(data.completion.rate * 100)}%`} detail={`${data.completion.completed} completed`} /><MetricCard label="Avg. duration" value={data.duration.averageMinutes === null ? "N/A" : `${Math.round(data.duration.averageMinutes)}m`} detail={`${data.duration.completedSamples} completed samples`} /></div>
    <div className="grid gap-5 lg:grid-cols-2"><section className="border border-[#303030] bg-[#171717] p-5"><h2 className="mb-5 text-lg font-semibold">Hiring funnel</h2><Bars items={[{ label: "Candidates", value: data.hiringFunnel.candidates }, { label: "Interviews created", value: data.hiringFunnel.invited }, { label: "Started", value: data.hiringFunnel.started }, { label: "Completed", value: data.hiringFunnel.completed }]} /></section><section className="border border-[#303030] bg-[#171717] p-5"><h2 className="mb-5 text-lg font-semibold">Score distribution</h2><Bars items={data.scoreDistribution.map((item) => ({ label: item.label, value: item.count }))} /></section><section className="border border-[#303030] bg-[#171717] p-5"><h2 className="mb-5 text-lg font-semibold">Competencies</h2>{data.competencyDistribution.length ? <Bars items={data.competencyDistribution.map((item) => ({ label: item.name, value: item.averageScore, detail: `${item.averageScore.toFixed(1)} avg / ${item.count}` }))} /> : <p className="text-sm text-[#777]">No completed competency evaluations in this period.</p>}</section><section className="border border-[#303030] bg-[#171717] p-5"><h2 className="mb-5 text-lg font-semibold">Open and drop-off states</h2>{data.dropOff.length ? <Bars items={data.dropOff.map((item) => ({ label: item.state.replaceAll("_", " "), value: item.count }))} /> : <p className="text-sm text-[#777]">No incomplete interviews in this period.</p>}</section></div>
    <section><h2 className="mb-3 text-lg font-semibold">Assessment performance</h2>{data.assessmentPerformance.length ? <div className="overflow-x-auto border border-[#303030] bg-[#171717]"><Table><thead><tr className="border-b border-[#303030] text-xs text-[#777]"><th className="p-4">Assessment</th><th className="p-4">Interviews</th><th className="p-4">Average score</th></tr></thead><tbody>{data.assessmentPerformance.map((item) => <tr key={item.assessmentId} className="border-b border-[#292929] last:border-0"><td className="p-4">{item.title}</td><td className="p-4">{item.interviews}</td><td className="p-4">{item.averageScore === null ? "Not scored" : item.averageScore.toFixed(1)}</td></tr>)}</tbody></Table></div> : <EmptyState title="No assessment performance yet" description="Performance appears after interviews are created for an assessment." />}</section></>}
  </div>;
}
