"use client";

import { useEffect, useState, type FormEvent } from "react";
import { apiRequest, getErrorMessage, type Organization } from "@/lib/api";
import { useRecruiterApp } from "./app-shell";
import { EmptyState, ErrorState, Input, PageSkeleton, Select, SubmitButton } from "./ui";
export function SettingsView() {
  const { organization } = useRecruiterApp(); const id = organization?.id ?? ""; const canEdit = organization?.role === "OWNER" || organization?.role === "ADMIN"; const [state, setState] = useState<{ key: string; data: Organization | null; error: string }>({ key: "", data: null, error: "" }); const [retry, setRetry] = useState(0); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (!id) return; let active = true; apiRequest<{ organization: Organization }>(`/organizations/${id}`, {}, id).then((data) => active && setState({ key: id, data: data.organization, error: "" })).catch((error) => active && setState({ key: id, data: null, error: getErrorMessage(error) })); return () => { active = false; }; }, [id, retry]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); const data = new FormData(event.currentTarget); try { const updated = await apiRequest<Organization>(`/organizations/${id}`, { method: "PATCH", body: JSON.stringify({ name: data.get("name"), slug: data.get("slug"), logoUrl: data.get("logoUrl"), industry: data.get("industry"), companySize: data.get("companySize") || undefined, timezone: data.get("timezone") }) }, id); setState({ key: id, data: updated, error: "" }); setMessage("Organization profile saved."); } catch (error) { setMessage(getErrorMessage(error)); } finally { setBusy(false); } }
  if (!organization) return <EmptyState title="No organization available" description="Select an organization to edit its profile." />; if (state.key !== id) return <PageSkeleton />; if (state.error || !state.data) return <ErrorState message={state.error} onRetry={() => setRetry((value) => value + 1)} />; const data = state.data;
  return <div className="mx-auto max-w-3xl space-y-7"><header><p className="font-mono text-[10px] uppercase tracking-widest text-[#ff4d1c]">Workspace settings</p><h1 className="mt-2 text-3xl font-semibold">Organization profile</h1><p className="mt-2 text-sm text-[#888]">{canEdit ? "Details used to identify this recruiter workspace." : "You have read-only access to this organization profile."}</p></header><form onSubmit={submit} className="grid gap-5 border border-[#303030] bg-[#171717] p-6 sm:grid-cols-2"><Input disabled={!canEdit} name="name" label="Organization name" defaultValue={data.name} required /><Input disabled={!canEdit} name="slug" label="Workspace slug" defaultValue={data.slug} required /><Input disabled={!canEdit} name="industry" label="Industry" defaultValue={data.industry ?? ""} /><Select disabled={!canEdit} name="companySize" label="Company size" defaultValue={data.companySize ?? ""}><option value="">Not specified</option><option value="SOLO">Solo</option><option value="SMALL">Small</option><option value="MEDIUM">Medium</option><option value="LARGE">Large</option><option value="ENTERPRISE">Enterprise</option></Select><Input disabled={!canEdit} name="logoUrl" type="url" label="Logo URL" defaultValue={data.logoUrl ?? ""} /><Input disabled={!canEdit} name="timezone" label="Timezone" defaultValue={data.timezone ?? "UTC"} required />{canEdit ? <div className="sm:col-span-2">{message ? <p role="status" className="mb-3 text-sm text-[#aaa]">{message}</p> : null}<SubmitButton busy={busy}>Save organization</SubmitButton></div> : null}</form></div>;
}
